// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace SW_Easy_Way.Interceptor.Infos
{
	public class RandomScroll
	{

		[JsonProperty("item_master_id")]
		public int ItemMasterId { get; set; }

		[JsonProperty("item_quantity")]
		public int ItemQuantity { get; set; }
	}

	public class UnitInfo
	{

		[JsonProperty("unit_id")]
		public long UnitId { get; set; }

		[JsonProperty("wizard_id")]
		public int WizardId { get; set; }

		[JsonProperty("island_id")]
		public int IslandId { get; set; }

		[JsonProperty("pos_x")]
		public int PosX { get; set; }

		[JsonProperty("pos_y")]
		public int PosY { get; set; }

		[JsonProperty("building_id")]
		public int BuildingId { get; set; }

		[JsonProperty("unit_master_id")]
		public int UnitMasterId { get; set; }

		[JsonProperty("unit_level")]
		public int UnitLevel { get; set; }

		[JsonProperty("class")]
		public int Class { get; set; }

		[JsonProperty("con")]
		public int Con { get; set; }

		[JsonProperty("atk")]
		public int Atk { get; set; }

		[JsonProperty("def")]
		public int Def { get; set; }

		[JsonProperty("spd")]
		public int Spd { get; set; }

		[JsonProperty("resist")]
		public int Resist { get; set; }

		[JsonProperty("accuracy")]
		public int Accuracy { get; set; }

		[JsonProperty("critical_rate")]
		public int CriticalRate { get; set; }

		[JsonProperty("critical_damage")]
		public int CriticalDamage { get; set; }

		[JsonProperty("experience")]
		public int Experience { get; set; }

		[JsonProperty("exp_gained")]
		public int ExpGained { get; set; }

		[JsonProperty("exp_gain_rate")]
		public int ExpGainRate { get; set; }

		[JsonProperty("skills")]
		public int[][] Skills { get; set; }

		[JsonProperty("runes")]
		public object[] Runes { get; set; }

		[JsonProperty("costume_master_id")]
		public int CostumeMasterId { get; set; }

		[JsonProperty("trans_items")]
		public object[] TransItems { get; set; }

		[JsonProperty("attribute")]
		public int Attribute { get; set; }

		[JsonProperty("create_time")]
		public string CreateTime { get; set; }

		[JsonProperty("source")]
		public int Source { get; set; }

		[JsonProperty("homunculus")]
		public int Homunculus { get; set; }

		[JsonProperty("homunculus_name")]
		public string HomunculusName { get; set; }
	}

	public class CraftStuff
	{

		[JsonProperty("wizard_id")]
		public int WizardId { get; set; }

		[JsonProperty("item_master_type")]
		public int ItemMasterType { get; set; }

		[JsonProperty("item_master_id")]
		public int ItemMasterId { get; set; }

		[JsonProperty("item_quantity")]
		public int ItemQuantity { get; set; }
	}

	public class Rune
	{

		[JsonProperty("rune_id")]
		public long RuneId { get; set; }

		[JsonProperty("wizard_id")]
		public int WizardId { get; set; }

		[JsonProperty("occupied_type")]
		public int OccupiedType { get; set; }

		[JsonProperty("occupied_id")]
		public int OccupiedId { get; set; }

		[JsonProperty("slot_no")]
		public int SlotNo { get; set; }

		[JsonProperty("rank")]
		public int Rank { get; set; }

		[JsonProperty("class")]
		public int Class { get; set; }

		[JsonProperty("set_id")]
		public int SetId { get; set; }

		[JsonProperty("upgrade_limit")]
		public int UpgradeLimit { get; set; }

		[JsonProperty("upgrade_curr")]
		public int UpgradeCurr { get; set; }

		[JsonProperty("base_value")]
		public int BaseValue { get; set; }

		[JsonProperty("sell_value")]
		public int SellValue { get; set; }

		[JsonProperty("pri_eff")]
		public int[] PriEff { get; set; }

		[JsonProperty("prefix_eff")]
		public int[] PrefixEff { get; set; }

		[JsonProperty("sec_eff")]
		public int[][] SecEff { get; set; }

		[JsonProperty("extra")]
		public int Extra { get; set; }
	}

	public class Crate
	{
		[JsonProperty("random_scroll")]
		public RandomScroll RandomScroll { get; set; }

		[JsonProperty("unit_info")]
		public UnitInfo UnitInfo { get; set; }

		[JsonProperty("craft_stuff")]
		public CraftStuff CraftStuff { get; set; }

		[JsonProperty("rune")]
		public Rune Rune { get; set; }
	}

	public class Reward
	{

		[JsonProperty("mana")]
		public int Mana { get; set; }

		[JsonProperty("crystal")]
		public int Crystal { get; set; }

		[JsonProperty("energy")]
		public int Energy { get; set; }

		[JsonProperty("crate")]
		public Crate Crate { get; set; }
	}

}
