// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.ComponentModel;
using Newtonsoft.Json;
using PropertyChanged;

namespace SW_Easy_Way.Interceptor.Infos
{
	public class WorldbossStatus : INotifyPropertyChanged
	{

		[JsonProperty("worldboss_id")]
		public int WorldbossId { get; set; }

		[JsonProperty("region_id")]
		public int RegionId { get; set; }

		[JsonProperty("status")]
		public int Status { get; set; }

		public event PropertyChangedEventHandler PropertyChanged;
	}

	public class NpcList : INotifyPropertyChanged
	{

		[JsonProperty("wizard_id")]
		public int WizardId { get; set; }

		[JsonProperty("wizard_level")]
		public int WizardLevel { get; set; }

		[JsonProperty("next_battle")]
		public int NextBattle { get; set; }

		public event PropertyChangedEventHandler PropertyChanged;
	}

	public class WizardInfo : INotifyPropertyChanged
	{

		[JsonProperty("wizard_id")]
		public int WizardId { get; set; }

		[JsonProperty("wizard_name")]
		public string WizardName { get; set; }

		[JsonProperty("wizard_mana")]
		public int WizardMana { get; set; }

		[JsonProperty("wizard_crystal")]
		public int WizardCrystal { get; set; }

		[JsonProperty("wizard_energy")]
		public int WizardEnergy { get; set; }

		[JsonProperty("arena_energy")]
		public int ArenaEnergy { get; set; }

		[JsonProperty("arena_energy_max")]
		public int ArenaEnergyMax { get; set; }

		[JsonProperty("energy_max")]
		public int EnergyMax { get; set; }

		[JsonProperty("social_point_current")]
		public int SocialPointCurrent { get; set; }

		[JsonProperty("social_point_max")]
		public int SocialPointMax { get; set; }

		[JsonProperty("honor_point")]
		public int HonorPoint { get; set; }

		[JsonProperty("guild_point")]
		public int GuildPoint { get; set; }

		public event PropertyChangedEventHandler PropertyChanged;
	}

	public class Wizard : INotifyPropertyChanged
	{
		[JsonIgnore]
		public string Name { get; set; }

		[JsonProperty("wizard_info")]
		public WizardInfo WizardInfo { get; set; }

		[JsonProperty("npc_list")]
		public NpcList[] NpcList { get; set; }

		[JsonProperty("worldboss_status")]
		public WorldbossStatus WorldbossStatus { get; set; }

		[JsonProperty("my_worldboss_daily_battle_count")]
		public int MyWorldbossDailyBattleCount { get; set; }

		public event PropertyChangedEventHandler PropertyChanged;
	}

}
